team_red: ["psilva1","psilva2","psilva3", "psilva4","psilva5"]
team_green: ["silvamfpedro","silvamfpedro2","silvamfpedro3","silvamfpedro4","silvamfpedro5"]
team_blue: ["pedrosilva1", "pedrosilva2", "pedrosilva3"]
